# Generated by Django 5.2.6 on 2025-09-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="otpverification",
            table="otp_verification",
        ),
    ]
