# Generated by Django 5.2.6 on 2025-09-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novalib", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
