# Generated by Django 5.2.6 on 2025-09-29 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novalib", "0002_user_otp_user_otp_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="autohrized",
            new_name="authorized",
        ),
    ]
