# Generated by Django 5.2.6 on 2025-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novalib", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_id",
            field=models.CharField(
                blank=True, editable=False, max_length=8, null=True, unique=True
            ),
        ),
    ]
