# Generated by Django 5.2.6 on 2025-10-09 10:33

import novalib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novalib", "0005_notification_notification_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="uploaded_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=novalib.models.notification_image_upload_path,
            ),
        ),
    ]
