# Generated by Django 5.2.7 on 2025-10-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novalib", "0007_developernotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_barcode", models.CharField(max_length=100, unique=True)),
                ("book_title", models.CharField(max_length=255)),
                ("auther", models.CharField(max_length=255)),
                ("avalible", models.BooleanField(default=True)),
                ("issued_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
