# Generated by Django 5.2.7 on 2025-10-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novalib", "0008_booksdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookslog",
            name="issued_date",
        ),
        migrations.RemoveField(
            model_name="bookslog",
            name="return_date",
        ),
        migrations.RemoveField(
            model_name="bookslog",
            name="user",
        ),
        migrations.AddField(
            model_name="booksdetail",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
