# Generated by Django 5.2.7 on 2025-10-25 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novalib", "0009_remove_bookslog_issued_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booksdetail",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_details",
                to="novalib.user",
            ),
        ),
    ]
